### PR TITLE
fix: cli multiple input

### PR DESCRIPTION
**Pull request by canerakdas**
## Description

With this PR, if the input pattern points to more than one file, we expect it to work for all of them. In the current version, it only produces output for the first file.

## Validation

For example, expect the command below to produce output for all markdown files in the `api` directory;
```sh
npx api-docs-tooling -i PATH_TO_NODE/doc/api/*.md -t json-simple -o .
```

### CODE REVIEW

**Comment by ovflowd** [comment]
Sorry, what exactly was not working? For me Im able to have this working with same arguments but `-i "/path/to/*.md"`

**Comment by canerakdas** [comment]
> Sorry, what exactly was not working? For me Im able to have this working with same arguments but `-i "/path/to/*.md"`

When I check for the `main` branch, `-i "/path/to/*.md"` gives me a JSON output of 268 lines containing only `addons` 🤔 

```json
{
  "version": "v20.11.1",
  "changelog": "https://raw.githubusercontent.com/nodejs/node/HEAD/CHANGELOG.md",
  "input": "../node/doc/api/addons.md",
  "target": [
    "json-simple"
  ],
  "output": "."
}
```

**Comment by ovflowd** [comment]
For me it work fine when I surround with quotes, but if this PR fixes it let's get it merged :)

**Comment by canerakdas** [comment]
> For me it work fine when I surround with quotes, but if this PR fixes it let's get it merged :)

Since it is a string array containing more than one file, at worst we fixing the input type 😄 Now I get it, it worked for me too when I added double quotes 👀

**Review by ovflowd — APPROVED** [review]

**Pull request merged**
