### PR TITLE
fix(tests): fix some tests that got out of sync with the code

### PR DESCRIPTION
**Pull request by flakey5**
## Description

Tests in main are broken, this pr aims to fix them. The most prominent issues were with type mismatches, presumably from when we switched to `unist`. 

I used the code as the source of truth since the changes to the responses were intentional from what I can tell

### CODE REVIEW

**Review by AugustinMauroy — APPROVED** [review]
LGTM !!! thanks for fixing that 😁

**Review by ovflowd — APPROVED** [review]
LGTM!

**Comment by ovflowd** [comment]
We should eventually start using snapshots!

**Comment by AugustinMauroy** [comment]
> We should eventually start using snapshots!

So we I'll need to use node 22

**Pull request merged**
